apiVersion: apps/v1
kind: Deployment
metadata:
  name: whitehouse23-deploy
  labels:
    app: whitehouse23-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whitehouse23-app
  template:
    metadata:
      labels:
        app: whitehouse23-app
    spec:
      containers:
      - name: whitehouse23-container
        image: whitehouse23/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whitehouse23-np-service
  labels:
    app: whitehouse23-np-app
spec:
  selector:
    app: whitehouse23-app
  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
